const express = require('express');
const mongoose = require('mongoose');
const cors = require('cors');
const path = require('path');

const app = express();
const PORT = process.env.PORT || 4000;

// Middleware
app.use(cors());
app.use(express.json());
app.use(express.static(path.join(__dirname, 'public')));

// MongoDB Connection from SpamSnare backend
const MONGODB_URI = 'mongodb+srv://admin:admin@pbcluster.dlcjogp.mongodb.net/?appName=PBCluster';

mongoose.connect(MONGODB_URI)
    .then(() => {
        console.log('Connected to SpamSnare MongoDB');
    }).catch(err => {
        console.error('MongoDB connection error:', err);
    });

// Mongoose Model representing SpamSnare's GenEmail
const GenEmailSchema = new mongoose.Schema({
    email: { type: String, required: true, unique: true },
    generatedAt: { type: Date, default: Date.now }
}, {
    timestamps: true,
    collection: 'gen_emails'
});

const Email = mongoose.model('GenEmail', GenEmailSchema);

// API Endpoints

// Get all emails generated by SpamSnare, sorted by latest
app.get('/api/emails', async (req, res) => {
    try {
        const emails = await Email.find().sort({ generatedAt: -1 });
        res.json(emails);
    } catch (error) {
        res.status(500).json({ error: 'Server error' });
    }
});

// Serve index.html for all other routes
app.use((req, res) => {
    res.sendFile(path.join(__dirname, 'public', 'index.html'));
});

app.listen(PORT, () => {
    console.log(`Demo Server is running on http://localhost:${PORT}`);
});
